name: "webhook"
repository: github.com/SpiralScout4Share/trivy-plugin-webhook
version: "0.4.2"
usage: trivy webhook -- <plugin args> -- <trivy args>
description: |-
  A Trivy plugin that sends the trivy results to a webhook endpoint.
  Usage: trivy webhook -- <plugin args> -- <trivy args>
platforms:
- selector:
    os: linux
    arch: amd64
  uri: https://github.com/SpiralScout4Share/trivy-plugin-webhook/releases/download/v0.4.2/trivy-webhook_0.4.2_Linux_64bit.tar.gz
  bin: ./trivy-webhook
